### ISSUE TITLE
Ledger: Use WebUSB and Increase timeouts for verification

### ISSUE THREAD

**Issue by My1** [Nault/Nault#145] opened 2020-08-11 02:57 UTC
apparently the site loses connectivity to the ledger while verification is happening, which kinda doesnt seem good because you are made to not properly verify your transactions.

this might or might not be a side effect of Nault still using U2F.

Also on Windows 10 this leads to annoying popups from Windows all the time, which is not fun.

switching over to webUSB should help though

https://github.com/LedgerHQ/ledgerjs

**Comment by aleksre** [comment] 2020-08-11 10:30
Duplicate of #13

**Comment by My1** [comment] 2020-08-11 10:45
sorry, although at least that issue did not mention that fact that the site seems to lose connection to the ledger on verification currently when taking too long

**Comment by BitDesert** [comment] 2020-08-11 15:58
It seems that WebUSB is not supported by Firefox because it's classified as "harmful": https://mozilla.github.io/standards-positions/#webusb
U2F works for the web good enough, if you want to skip the popups you can use the desktop app: https://github.com/Nault/Nault/releases/latest

**Comment by My1** [comment] 2020-08-11 16:02
I am still on 8.1 so the pop-ups are not the issue, for me at least. The issue are the timeouts that don't let me properly read the stuff on the display.

**Closed as completed** 2020-11-04 10:33 UTC
Labels: duplicate, enhancement
