### ISSUE TITLE
Node information

### ISSUE THREAD

**Issue by guilhermelawless** [Nault/Nault#50] opened 2020-07-09 13:02 UTC
A [hidden?] page that grabs node information from the RPC could be used for some quick troubleshooting, or general information for those using a custom backend node. Maybe some of them are useful in other pages.

Some useful stats, as usually:
- Block and uncemented count from RPC block_count
- Which network:  main(live) / beta from RPC version
- Telemetry things from RPC telemetry using optionals **address** and **port** to target only the local node information. Unfortunately it would be necesssary to assume (or config option) the local peering port (7075 main net, 54000 beta). Will take a look into potesntially making this simpler for V22.

**Comment by Joohansson** [comment] 2020-07-09 19:44
I think it's a good idea, especially block count. That's something I'm planning for TIX wallet too because if the network is under heavy load some transactions may not come through. Then it will be interesting to compare different backends. So maybe confirmed block count make most sense for that?

The other stats also require more commands to be allowed by the backends but not a big deal. At least the block count I think should be available for the normal user. Maybe some advance button somewhere.

**Closed as completed** 2020-07-18 19:51 UTC
Labels: enhancement
