### ISSUE TITLE
manage multiple wallets

### ISSUE THREAD

**Issue by milahu** [Nault/Nault#626] opened 2024-07-10 08:06 UTC
my wallet is locked, and i forgot my password. now what?

i want to create a new wallet but keep the old one
but i dont see a way to do this

~~i only see "add new account" but no "add new wallet"~~

in `settings > manage wallet`
i cannot backup or export my wallet because it is locked

in `settings > configure new wallet`
i can create a new wallet, but then i lose my old wallet

i guess as a workaround i could save the app state (localstorage ...)
reset the app state, and create a new wallet ...
but having multiple wallets should be a first class feature

**Comment by keerifox** [comment] 2024-07-10 17:32
duplicate of #28, please refer to that issue on how to have multiple wallets

**Closed as completed by keerifox** 2024-07-10 17:32 UTC
Labels: enhancement
