### ISSUE TITLE
Sign macOS releases

### ISSUE THREAD

**Issue by t-anon** [Nault/Nault#396] opened 2021-06-03 05:08 UTC
**Is your feature request related to a problem? Please describe.**

Currently, when you download Nault on macOS, it is unsigned and macOS throws a warning. You have to right-click -> Open to bypass the warning.

UX aside, from a security point of view, cryptocurrency apps should be signed so we can be sure that the blob we are downloading was compiled by a developer we trust.

**Describe the solution you'd like**

Sign your release.

**Describe alternatives you've considered**

There isn't an alternative. 

**Additional context**

It is difficult to trust unsigned applications. Releases should be signed by trusted developers.

**Comment by Joohansson** [comment] 2021-06-03 05:37
As nice as it would be, nault is a community-driven free and not for profit application. There is no one here willing to pay $200-$500 per year for a certificate. It's the same limitation for all OS. Not even the Nano node software is signed.

**Comment by keerifox** [comment] 2021-06-03 09:21
Duplicate of #244

**Closed as completed by keerifox** 2021-06-03 09:21 UTC
Labels: enhancement
